database_url = "postgresql://dev:dev-db@localhost:5432/dimdimhealthdev"
redis_url = "redis://localhost:6379/"

frontend_url = "http://localhost:8081"
listenner_addr = "0.0.0.0:3000"

env_filter = "dimdim_health=debug,tower_http=debug"

jwt_secret = "dev_jwt_secret_key"

number_workers = 5

gmail_email = "dimdimhealth@gmail.com"
# gmail_password is defined in common.toml
